import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $users: i.entity({
      displayName: i.string().optional(),
    }),
    events: i.entity({
      organizerId: i.string().optional(),
      title: i.string().optional(),
      eventName: i.string().optional(),
      description: i.string().optional(),
      startDateTime: i.string().optional(),
      postCode: i.string().optional(),
      address: i.string().optional(),
      venueName: i.string().optional(),
      costType: i.string().optional(),
      cost: i.string().optional(),
      accessibility: i.string().optional(),
      bookingUrl: i.string().optional(),
      primaryCategory: i.string().optional(),
      tags: i.string().optional(),
      eventType: i.string().optional(),
      priceBand: i.string().optional(),
      musicType: i.string().optional(),
      creativeType: i.string().optional(),
      learningType: i.string().optional(),
      socialLevel: i.string().optional(),
      eventFormat: i.string().optional(),
      meetingPeople: i.string().optional(),
      eventTime: i.string().optional(),
      durationBand: i.string().optional(),
      transport: i.string().optional(),
      stepFree: i.string().optional(),
      noise: i.string().optional(),
      seating: i.string().optional(),
      primaryBenefit: i.string().optional(),
      eventMood: i.string().optional(),
      lgbtqFocus: i.string().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
    }),
    solo_events: i.entity({
      title: i.string().optional(),
      eventName: i.string().optional(),
      description: i.string().optional(),
      startDateTime: i.string().optional(),
      postCode: i.string().optional(),
      address: i.string().optional(),
      venueName: i.string().optional(),
      costType: i.string().optional(),
      cost: i.string().optional(),
      accessibility: i.string().optional(),
      bookingUrl: i.string().optional(),
      primaryCategory: i.string().optional(),
      tags: i.string().optional(),
      eventType: i.string().optional(),
      priceBand: i.string().optional(),
      musicType: i.string().optional(),
      creativeType: i.string().optional(),
      learningType: i.string().optional(),
      socialLevel: i.string().optional(),
      eventFormat: i.string().optional(),
      meetingPeople: i.string().optional(),
      eventTime: i.string().optional(),
      durationBand: i.string().optional(),
      transport: i.string().optional(),
      stepFree: i.string().optional(),
      noise: i.string().optional(),
      seating: i.string().optional(),
      primaryBenefit: i.string().optional(),
      eventMood: i.string().optional(),
      lgbtqFocus: i.string().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
    }),
    questionnaire_responses: i.entity({
      questionId: i.string(),
      selectedOptionIds: i.json(),
      lat: i.number().optional(),
      lng: i.number().optional(),
      userId: i.string().optional(),
      createdAt: i.number(),
    }),
    user_settings: i.entity({
      userId: i.string(),
      notificationsEnabled: i.boolean(),
      locationSharingEnabled: i.boolean(),
      profileVisibility: i.string(),
    }),
    voice_posts: i.entity({
      body: i.string(),
      createdAt: i.number().indexed(),
      category: i.string().optional(),
      postCode: i.string().optional(),
      socialLevel: i.string().optional(),
      preferredTime: i.string().optional(),
      groupSize: i.string().optional(),
    }),
    voice_post_comments: i.entity({
      body: i.string(),
      createdAt: i.number().indexed(),
    }),
    quiet_slots: i.entity({
      hostId: i.string(),
      date: i.string(),
      startTime: i.string(),
      endTime: i.string(),
      label: i.string().optional(),
      status: i.string(),
      createdAt: i.number().indexed(),
    }),
    friend_requests: i.entity({
      fromId: i.string(),
      toId: i.string(),
      status: i.string(),
      createdAt: i.number(),
      toEmail: i.string().optional(),
      fromEmail: i.string().optional(),
    }),
    group_memberships: i.entity({
      userId: i.string(),
      groupName: i.string(),
    }),
    user_locations: i.entity({
      userId: i.string(),
      lat: i.number(),
      lng: i.number(),
    }),
    conversations: i.entity({
      participant1Id: i.string(),
      participant2Id: i.string(),
      createdAt: i.number().indexed(),
      participant1LastReadAt: i.number().optional(),
      participant2LastReadAt: i.number().optional(),
    }),
    messages: i.entity({
      conversationId: i.string(),
      senderId: i.string(),
      body: i.string(),
      createdAt: i.number().indexed(),
    }),
    event_bookings: i.entity({
      userId: i.string(),
      eventId: i.string(),
      /** "events" | "solo_events" */
      source: i.string(),
      createdAt: i.number().indexed(),
    }),
    daily_prompt_responses: i.entity({
      userId: i.string(),
      promptId: i.string(),
      /** YYYY-MM-DD local date — one response per prompt per day */
      localDate: i.string(),
      scaleValue: i.number().optional(),
      selectedOptionIds: i.json().optional(),
      createdAt: i.number().indexed(),
    }),
    health_daily_summaries: i.entity({
      userId: i.string(),
      /** YYYY-MM-DD */
      date: i.string(),
      steps: i.number().optional(),
      distanceKm: i.number().optional(),
      activeEnergyKcal: i.number().optional(),
      exerciseMinutes: i.number().optional(),
      workoutCount: i.number().optional(),
      createdAt: i.number().indexed(),
    }),
  },
  links: {
    postAuthor: {
      forward: { on: "voice_posts", has: "one", label: "author" },
      reverse: { on: "$users", has: "many", label: "authoredPosts" },
    },
    postUpvotes: {
      forward: { on: "voice_posts", has: "many", label: "upvotedBy" },
      reverse: { on: "$users", has: "many", label: "upvotedPosts" },
    },
    postComment: {
      forward: { on: "voice_post_comments", has: "one", label: "post" },
      reverse: { on: "voice_posts", has: "many", label: "comments" },
    },
    commentAuthor: {
      forward: { on: "voice_post_comments", has: "one", label: "author" },
      reverse: { on: "$users", has: "many", label: "voicePostComments" },
    },
    friendRequestFrom: {
      forward: { on: "friend_requests", has: "one", label: "from" },
      reverse: { on: "$users", has: "many", label: "sentFriendRequests" },
    },
    friendRequestTo: {
      forward: { on: "friend_requests", has: "one", label: "to" },
      reverse: { on: "$users", has: "many", label: "receivedFriendRequests" },
    },
    groupMembershipUser: {
      forward: { on: "group_memberships", has: "one", label: "user" },
      reverse: { on: "$users", has: "many", label: "groupMemberships" },
    },
    userLocationUser: {
      forward: { on: "user_locations", has: "one", label: "user" },
      reverse: { on: "$users", has: "many", label: "userLocation" },
    },
    conversationParticipant1: {
      forward: { on: "conversations", has: "one", label: "participant1" },
      reverse: { on: "$users", has: "many", label: "conversationsAsParticipant1" },
    },
    conversationParticipant2: {
      forward: { on: "conversations", has: "one", label: "participant2" },
      reverse: { on: "$users", has: "many", label: "conversationsAsParticipant2" },
    },
    messageConversation: {
      forward: { on: "messages", has: "one", label: "conversation" },
      reverse: { on: "conversations", has: "many", label: "messages" },
    },
    messageSender: {
      forward: { on: "messages", has: "one", label: "sender" },
      reverse: { on: "$users", has: "many", label: "sentMessages" },
    },
    eventLikes: {
      forward: { on: "events", has: "many", label: "likedBy" },
      reverse: { on: "$users", has: "many", label: "likedEvents" },
    },
    quietSlotHost: {
      forward: { on: "quiet_slots", has: "one", label: "host" },
      reverse: { on: "$users", has: "many", label: "quietSlots" },
    },
  },
});

type AppSchema = typeof _schema;
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
