import { i } from "@instantdb/react";

const _schema = i.schema({
  entities: {
    $users: i.entity({
      displayName: i.string().optional(),
    }),
    events: i.entity({
      organizerId: i.string().optional(),
      title: i.string().optional(),
      eventName: i.string().optional(),
      description: i.string().optional(),
      startDateTime: i.string().optional(),
      postCode: i.string().optional(),
      address: i.string().optional(),
      venueName: i.string().optional(),
      costType: i.string().optional(),
      cost: i.string().optional(),
      accessibility: i.string().optional(),
      bookingUrl: i.string().optional(),
      primaryCategory: i.string().optional(),
      tags: i.string().optional(),
      eventType: i.string().optional(),
      priceBand: i.string().optional(),
      musicType: i.string().optional(),
      creativeType: i.string().optional(),
      learningType: i.string().optional(),
      socialLevel: i.string().optional(),
      eventFormat: i.string().optional(),
      meetingPeople: i.string().optional(),
      eventTime: i.string().optional(),
      durationBand: i.string().optional(),
      transport: i.string().optional(),
      stepFree: i.string().optional(),
      noise: i.string().optional(),
      seating: i.string().optional(),
      primaryBenefit: i.string().optional(),
      eventMood: i.string().optional(),
      lgbtqFocus: i.string().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
    }),
    solo_events: i.entity({
      title: i.string().optional(),
      eventName: i.string().optional(),
      description: i.string().optional(),
      startDateTime: i.string().optional(),
      postCode: i.string().optional(),
      address: i.string().optional(),
      venueName: i.string().optional(),
      costType: i.string().optional(),
      cost: i.string().optional(),
      accessibility: i.string().optional(),
      bookingUrl: i.string().optional(),
      primaryCategory: i.string().optional(),
      tags: i.string().optional(),
      eventType: i.string().optional(),
      priceBand: i.string().optional(),
      musicType: i.string().optional(),
      creativeType: i.string().optional(),
      learningType: i.string().optional(),
      socialLevel: i.string().optional(),
      eventFormat: i.string().optional(),
      meetingPeople: i.string().optional(),
      eventTime: i.string().optional(),
      durationBand: i.string().optional(),
      transport: i.string().optional(),
      stepFree: i.string().optional(),
      noise: i.string().optional(),
      seating: i.string().optional(),
      primaryBenefit: i.string().optional(),
      eventMood: i.string().optional(),
      lgbtqFocus: i.string().optional(),
      lat: i.number().optional(),
      lng: i.number().optional(),
    }),
    questionnaire_responses: i.entity({
      questionId: i.string(),
      selectedOptionIds: i.json(),
      lat: i.number().optional(),
      lng: i.number().optional(),
      userId: i.string().optional(),
      createdAt: i.number(),
    }),
    user_settings: i.entity({
      userId: i.string(),
      notificationsEnabled: i.boolean(),
      locationSharingEnabled: i.boolean(),
      profileVisibility: i.string(),
    }),
    voice_posts: i.entity({
      body: i.string(),
      createdAt: i.number().indexed(),
      category: i.string().optional(),
      postCode: i.string().optional(),
    }),
    friend_requests: i.entity({
      fromId: i.string(),
      toId: i.string(),
      status: i.string(),
      createdAt: i.number(),
    }),
    group_memberships: i.entity({
      userId: i.string(),
      groupName: i.string(),
    }),
    user_locations: i.entity({
      userId: i.string(),
      lat: i.number(),
      lng: i.number(),
    }),
  },
  links: {
    postAuthor: {
      forward: { on: "voice_posts", has: "one", label: "author" },
      reverse: { on: "$users", has: "many", label: "authoredPosts" },
    },
    postUpvotes: {
      forward: { on: "voice_posts", has: "many", label: "upvotedBy" },
      reverse: { on: "$users", has: "many", label: "upvotedPosts" },
    },
    friendRequestFrom: {
      forward: { on: "friend_requests", has: "one", label: "from" },
      reverse: { on: "$users", has: "many", label: "sentFriendRequests" },
    },
    friendRequestTo: {
      forward: { on: "friend_requests", has: "one", label: "to" },
      reverse: { on: "$users", has: "many", label: "receivedFriendRequests" },
    },
    groupMembershipUser: {
      forward: { on: "group_memberships", has: "one", label: "user" },
      reverse: { on: "$users", has: "many", label: "groupMemberships" },
    },
    userLocationUser: {
      forward: { on: "user_locations", has: "one", label: "user" },
      reverse: { on: "$users", has: "many", label: "userLocation" },
    },
  },
});

type AppSchema = typeof _schema;
const schema: AppSchema = _schema;

export type { AppSchema };
export default schema;
