/**
 * Synthetic community-interest lines merged into host AI suggestions and
 * offered as tap-to-append starters on Your Voice. Keeps generation broad
 * when real posts are thin or narrow.
 */
export const VOICE_BREADTH_SEEDS: readonly string[] = [
  "Anyone up for a beginner bouldering social in BS3?",
  "Looking for a relaxed life drawing class that welcomes first-timers.",
  "Would love a weekday lunchtime meditation drop-in near Bedminster.",
  "Is there a community choir that does not require auditions?",
  "Seeking a friendly chess club for adults who are a bit rusty.",
  "Parents: soft play meetup for toddlers followed by coffee?",
  "Who would join a Saturday parkrun-style 5K group from Southville?",
  "Hoping for a zero-waste swap shop or repair cafe in the area.",
  "Any interest in a monthly documentary screening plus discussion?",
  "Looking for a women-only swimming confidence session.",
  "Beginner ukulele circle would be brilliant if someone hosted it.",
  "Would anyone come to a Sunday morning yoga in the park (weather permitting)?",
  "Seeking a dads-and-kids football kickabout, all abilities.",
  "Is there a local writers group for short fiction, not poetry only?",
  "Looking for a gentle cycling group for people getting back on bikes.",
  "Would love a fermentation and sourdough workshop.",
  "Anybody want a board games night that is not just Catan?",
  "Hoping for a LGBTQ+ friendly pub quiz team night.",
  "Seeking a book club that reads contemporary translated fiction.",
  "Would join a monthly philosophy cafe in plain English.",
  "Looking for a stress-free public speaking practice group.",
  "Any interest in a community orchestra for rusty players?",
  "Hoping for a toddler music session that is not overly loud.",
  "Who would come to a learn-to-sketch urban sketching walk?",
  "Seeking a menopause wellness talk and peer support morning.",
  "Would love a seed swap and allotment tips session.",
  "Anybody up for a monthly science cafe with local researchers?",
  "Looking for a slow stitch and textile crafts afternoon.",
  "Hoping for a beginner salsa or bachata social class.",
  "Would join a local history walk ending at a cafe.",
  "Seeking a tabletop RPG one-shot night for newcomers.",
  "Any interest in a mindful walking group without phones?",
  "Looking for a parent-and-baby film morning with lower volume.",
  "Would love a community jazz jam where beginners can sit in.",
  "Hoping for a coding club for curious adults, not career switchers only.",
  "Seeking a creative writing sprint with prompts, no crit pressure.",
  "Anybody want a monthly vinyl listening night?",
  "Looking for a gentle stretch class for desk workers.",
  "Would join a Saturday brunch language exchange (any language).",
  "Hoping for a wildlife and birdwatching intro walk.",
  "Seeking a casual running club that allows walk-run intervals.",
  "Any interest in a pottery hand-building taster for two hours?",
  "Looking for a sober social evening with mocktails and games.",
  "Would love a community choir open mic rehearsal visitors welcome.",
  "Hoping for a resume and interview skills peer workshop.",
  "Seeking a monthly poetry open mic with a supportive vibe.",
  "Anybody up for a beginner bridge lesson series?",
  "Looking for a carers coffee morning with optional speaker.",
  "Would join a Sunday roast club that rotates venues.",
  "Hoping for a film photography darkroom taster day.",
  "Seeking a neurodiversity-friendly social meetup in a quiet space.",
  "Any interest in a community fridge cooking demo?",
  "Looking for a strength training class for complete beginners.",
  "Would love a monthly comedy new material night locally.",
  "Hoping for a family-friendly nature scavenger hunt.",
  "Seeking a sewing machine basics fix-your-hem workshop.",
  "Anybody want a casual darts and pool league social?",
  "Looking for a grief and loss peer listening circle, facilitated.",
  "Would join a monthly astronomy stargazing if skies allow.",
  "Hoping for a drag and cabaret variety night in a small venue.",
  "Seeking a beginner indoor climbing buddy matching evening.",
  "Any interest in a fermentation zero-alcohol drinks tasting?",
  "Looking for a resume-free networking for freelancers.",
  "Would love a community orchestra open day try an instrument.",
  "Hoping for a toddler messy play session with easy cleanup space.",
  "Seeking a mindful colouring and tea afternoon for over 55s.",
  "Anybody up for a retro video games tournament casual?",
  "Looking for a walking book club discuss while you stroll.",
  "Would join a monthly fix-it clinic for bikes and small repairs.",
  "Hoping for a creative careers panel for young people locally.",
  "Seeking a gentle mat pilates class with chair options.",
  "Any interest in a sourdough pizza oven community night?",
  "Looking for a peer-led anxiety toolkit workshop, not therapy.",
  "Would love a local authors reading and signing evening.",
  "Hoping for a parent mental health walk-and-talk group.",
  "Seeking a beginner embroidery and visible mending session.",
  "Anybody want a monthly puzzle and escape-room enthusiasts meet?",
  "Looking for a choir that learns one song per month only.",
  "Would join a cold water dip safety briefing and buddy group.",
  "Hoping for a film club dedicated to Black British cinema.",
  "Seeking a casual volleyball session on sand or grass.",
  "Any interest in a home barista coffee tasting morning?",
  "Looking for a D and D character creation help for first-timers.",
  "Would love a community mural design feedback session.",
  "Hoping for a beginner weightlifting form clinic for women.",
  "Seeking a monthly climate action planning meetup, practical tasks.",
  "Anybody up for a printmaking linocut taster evening?",
  "Looking for a slow ramblers group under five miles.",
  "Would join a spoken word storytelling night true stories only.",
  "Hoping for a babywearing and new parent social walk.",
  "Seeking a digital declutter and privacy basics workshop.",
  "Any interest in a community choir carol prep starting in autumn?",
  "Looking for a peer maths help drop-in for GCSE parents.",
  "Would love a monthly craft beer and local food pairing.",
  "Hoping for a wheelchair-accessible gardening session.",
  "Seeking a beginner harmonica workshop in one afternoon.",
  "Anybody want a casual scrabble and word games afternoon?",
  "Looking for a reiki share circle if certified practitioners exist.",
  "Would join a monthly architecture and urban design walk.",
  "Hoping for a teen-safe open mic for music and poetry.",
  "Seeking a bread and soup community lunch pay what you can.",
  "Any interest in a local election hustings in a neutral venue?",
  "Looking for a gentle aqua aerobics trial for non-swimmers cautious.",
  "Would love a zine-making and distro meetup.",
  "Hoping for a beginner macrame plant hanger workshop.",
  "Seeking a monthly co-working with accountability pomodoros.",
  "Anybody up for a community flash choir one afternoon only?",
  "Looking for a peer-led stretch for chronic pain friendly pacing.",
  "Would join a board game design playtest night for prototypes.",
  "Hoping for a riverside cleanup plus picnic social.",
  "Seeking a beginner DJ and open decks evening with coaching.",
  "Any interest in a multilingual story time for under-fives?",
  "Looking for a casual petanque or boules league near a cafe.",
  "Would love a monthly film shorts night from local filmmakers.",
  "Hoping for a strength and balance class for fall prevention.",
  "Seeking a community timebank skill swap launch event.",
  "Anybody want a relaxed Sunday acoustic session in a beer garden?",
  "Looking for a peer support group for new small business owners.",
  "Would join a monthly foraging rules-and-safety intro talk.",
  "Hoping for a beginner crochet granny square social.",
  "Seeking a quiet reading room social with tea, no small talk required.",
  "Any interest in a community-led local news and ideas forum?",
];
